/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                /* @} */

/*! @name PORTE20 (number 13), J10[1]
  @{ */
#define BOARD_INITPINS_POT_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_POT_PIN 20U    /*!<@brief PORTE pin index: 20 */
                                      /* @} */

/*! @name PORTE22 (number 15), J10[5]
  @{ */
#define BOARD_INITPINS_BOTON_3_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_BOTON_3_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_BOTON_3_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_BOTON_3_PIN 22U    /*!<@brief PORTE pin index: 22 */
                                          /* @} */

/*! @name PORTE23 (number 16), J10[7]
  @{ */
#define BOARD_INITPINS_BOTON_1_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_BOTON_1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_BOTON_1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_BOTON_1_PIN 23U    /*!<@brief PORTE pin index: 23 */
                                          /* @} */

/*! @name PORTE21 (number 14), J10[3]
  @{ */
#define BOARD_INITPINS_BOTON_2_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_BOTON_2_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_BOTON_2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_BOTON_2_PIN 21U    /*!<@brief PORTE pin index: 21 */
                                          /* @} */

/*! @name PORTE29 (number 21), J10[9]
  @{ */
#define BOARD_INITPINS_LED_PWM_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LED_PWM_PIN 29U    /*!<@brief PORTE pin index: 29 */
                                          /* @} */

/*! @name PORTE5 (number 6), J9[15]
  @{ */
#define BOARD_INITPINS_LED1_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LED1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LED1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LED1_PIN 5U     /*!<@brief PORTE pin index: 5 */
                                       /* @} */

/*! @name PORTE4 (number 5), J9[13]
  @{ */
#define BOARD_INITPINS_LED2_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LED2_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LED2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LED2_PIN 4U     /*!<@brief PORTE pin index: 4 */
                                       /* @} */

/*! @name PORTE2 (number 3), J9[9]
  @{ */
#define BOARD_INITPINS_CANCION_B0_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_CANCION_B0_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_CANCION_B0_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_CANCION_B0_PIN 2U     /*!<@brief PORTE pin index: 2 */
                                             /* @} */

/*! @name PORTE3 (number 4), J9[11]
  @{ */
#define BOARD_INITPINS_CANCION_B1_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_CANCION_B1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_CANCION_B1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_CANCION_B1_PIN 3U     /*!<@brief PORTE pin index: 3 */
                                             /* @} */

/*! @name PORTE30 (number 22), J10[11]
  @{ */
#define BOARD_INITPINS_LED0_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LED0_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LED0_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LED0_PIN 30U    /*!<@brief PORTE pin index: 30 */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
